прописать классы  
прописать элементы игры  
вывести результаты

In [3]:
import numpy as np

In [179]:
class Channels(): ## матрица связей каналов
    
    def __init__(self, graph_status):
        
        self.graph_status = graph_status
        self.graph = np.zeros((100, 100), int)
        
        if self.graph_status:
            for i in range(100):
                for j in range(100):
                    if np.random.binomial(n = 1, p = 0.5) > 0:
                        self.graph[i][j] = np.random.poisson(10, 1)

In [341]:
a = Channels(True).graph
a

array([[11,  0,  9, ...,  7, 18,  0],
       [ 0,  0,  0, ...,  0, 10,  0],
       [ 0,  0,  0, ..., 11, 11,  9],
       ...,
       [ 0,  7,  0, ...,  7,  0, 13],
       [ 6, 10,  8, ...,  2,  7, 13],
       [ 0,  0,  0, ...,  0,  0,  8]])

In [109]:
class Users(): ## юзеры с подписками на каналы
    ## УБРАТЬ ПОВТОРЯЮЩИЕСЯ ПОДПИСКИ
    def __init__(self):
        self.read = [np.random.choice(np.arange(0, 99), np.random.randint(1, 11), replace=False) for i in range(5000)]

In [108]:
np.random.choice(np.arange(0, 99), np.random.randint(1, 11), replace=False)

array([45, 48, 78, 61])

In [112]:
for i in users:
    if len(i) != len(set(i)):
        print(i)

In [111]:
users = Users().__dict__['read']

In [102]:
users

[array([19, 42, 28, 64, 37, 94]),
 array([75, 46, 28, 22, 63, 91, 39]),
 array([50, 94]),
 array([34,  2, 90, 27, 44, 16, 83, 20]),
 array([61, 80, 98, 49, 50, 70, 84, 45, 64]),
 array([57, 68, 13, 14, 70, 66, 96, 93, 79]),
 array([ 1, 47]),
 array([48, 37, 12, 83]),
 array([ 6, 38, 58, 49,  5, 67, 63]),
 array([54, 61]),
 array([36, 68, 66, 78, 86, 14, 87]),
 array([62, 16]),
 array([ 4, 53]),
 array([55, 69, 47, 98, 31, 81]),
 array([ 9, 30, 52]),
 array([65, 89, 87, 58, 32, 23, 45]),
 array([65, 40, 41, 79, 13,  0, 79, 91]),
 array([82, 60, 32, 21, 61, 55, 69]),
 array([34, 40, 95, 55, 25, 63, 63]),
 array([65, 39, 12, 42, 85, 42]),
 array([94, 71, 71, 38, 60, 79, 78, 94]),
 array([30, 89, 72, 26, 80, 12, 87, 73]),
 array([26, 31, 17, 13, 96, 79]),
 array([48, 42, 81, 76]),
 array([ 8, 92]),
 array([52, 85, 83, 88, 18, 83,  6]),
 array([97, 81, 81]),
 array([23, 49, 23, 39, 38,  2]),
 array([26,  9,  1, 44]),
 array([51, 45, 21]),
 array([49, 38]),
 array([62, 98, 92,  5, 17, 55, 82

In [91]:
np.random.randint(0, 99, 5)

array([88, 37, 37,  5, 72])

In [352]:
 Users().__dict__['read']

array([list([31, 37, 46, 58, 94, 43, 86, 55]), list([41, 80]),
       list([54, 32, 1, 18, 94]), ...,
       list([43, 55, 58, 48, 46, 69, 95, 48, 44, 31]),
       list([83, 40, 29, 5, 87, 10, 49, 56]),
       list([55, 69, 10, 8, 28, 48])], dtype=object)

In [353]:
 Users().__dict__['read'].shape

(5000,)

In [357]:
class Publications: ## публикация постов - сенситивные/несенситивные
    
    def __init__(self):
        self.sensitive = np.zeros(100, int)
        for i in range(100):
            self.sensitive[i] = np.random.binomial(n = 1, p = 0.3)

In [372]:
Publications().sensitive

array([0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0])

In [ ]:
class Channels(): ## матрица связей каналов
    
    def __init__(self, graph_status):
        
        self.graph_status = graph_status
        self.graph = np.zeros((100, 100), int)
        
        if self.graph_status:
            for i in range(100):
                for j in range(100):
                    if np.random.binomial(n = 1, p = 0.5) > 0:
                        self.graph[i][j] = np.random.poisson(10, 1)
                        
        self.n_followers = np.zeros(100, dict)
        for i in range(100)    
            for i in range(5000):
                self.n_followers[i+1] = 

In [30]:
n_followers = np.zeros(100, {})
n_followers[1] = 11

In [60]:
users = Users().__dict__['read']

In [61]:
users

array([list([8, 1]), list([65, 54, 59, 4]), list([3, 19, 12, 12]), ...,
       list([21, 53, 78, 79, 15, 60, 57, 31]),
       list([1, 32, 9, 59, 54, 89, 48, 1, 28]),
       list([72, 36, 36, 81, 31, 97, 51, 36, 0, 16])], dtype=object)

In [78]:
users[10]

[65, 0, 14, 39, 42, 19, 50]

In [84]:
n_followers[0]

3

In [83]:
import numpy as np
n_followers = np.zeros(100, list)
for i in range(100):
    for j in range(50):
        if i in users[j]:
            print('i:', i, 'j:', j)
            n_followers[i] += 1 
            print(n_followers[i])

i: 0 j: 10
1
i: 0 j: 18
2
i: 0 j: 39
3
i: 1 j: 0
1
i: 1 j: 5
2
i: 1 j: 11
3
i: 1 j: 17
4
i: 1 j: 22
5
i: 2 j: 18
1
i: 3 j: 2
1
i: 3 j: 29
2
i: 3 j: 42
3
i: 3 j: 43
4
i: 4 j: 1
1
i: 4 j: 27
2
i: 4 j: 29
3
i: 5 j: 9
1
i: 6 j: 16
1
i: 6 j: 26
2
i: 6 j: 27
3
i: 6 j: 41
4
i: 7 j: 23
1
i: 7 j: 41
2
i: 7 j: 47
3
i: 8 j: 0
1
i: 8 j: 6
2
i: 8 j: 11
3
i: 8 j: 21
4
i: 8 j: 29
5
i: 8 j: 33
6
i: 9 j: 13
1
i: 9 j: 20
2
i: 9 j: 23
3
i: 10 j: 15
1
i: 10 j: 37
2
i: 11 j: 42
1
i: 12 j: 2
1
i: 12 j: 26
2
i: 13 j: 26
1
i: 14 j: 10
1
i: 15 j: 14
1
i: 15 j: 19
2
i: 15 j: 30
3
i: 15 j: 32
4
i: 15 j: 33
5
i: 15 j: 39
6
i: 15 j: 48
7
i: 16 j: 21
1
i: 16 j: 26
2
i: 16 j: 35
3
i: 17 j: 38
1
i: 17 j: 47
2
i: 18 j: 30
1
i: 18 j: 35
2
i: 18 j: 36
3
i: 18 j: 41
4
i: 18 j: 42
5
i: 19 j: 2
1
i: 19 j: 10
2
i: 20 j: 5
1
i: 20 j: 14
2
i: 20 j: 17
3
i: 20 j: 21
4
i: 20 j: 26
5
i: 20 j: 27
6
i: 20 j: 35
7
i: 21 j: 5
1
i: 21 j: 11
2
i: 21 j: 14
3
i: 21 j: 25
4
i: 21 j: 34
5
i: 22 j: 33
1
i: 23 j: 3
1
i: 23 j: 8
2
i: 23 j: 3

In [76]:
for i in range(100):
    for j in range(50):
        print(i, j)

0 0
0 1
0 2
0 3
0 4
0 5
0 6
0 7
0 8
0 9
0 10
0 11
0 12
0 13
0 14
0 15
0 16
0 17
0 18
0 19
0 20
0 21
0 22
0 23
0 24
0 25
0 26
0 27
0 28
0 29
0 30
0 31
0 32
0 33
0 34
0 35
0 36
0 37
0 38
0 39
0 40
0 41
0 42
0 43
0 44
0 45
0 46
0 47
0 48
0 49
1 0
1 1
1 2
1 3
1 4
1 5
1 6
1 7
1 8
1 9
1 10
1 11
1 12
1 13
1 14
1 15
1 16
1 17
1 18
1 19
1 20
1 21
1 22
1 23
1 24
1 25
1 26
1 27
1 28
1 29
1 30
1 31
1 32
1 33
1 34
1 35
1 36
1 37
1 38
1 39
1 40
1 41
1 42
1 43
1 44
1 45
1 46
1 47
1 48
1 49
2 0
2 1
2 2
2 3
2 4
2 5
2 6
2 7
2 8
2 9
2 10
2 11
2 12
2 13
2 14
2 15
2 16
2 17
2 18
2 19
2 20
2 21
2 22
2 23
2 24
2 25
2 26
2 27
2 28
2 29
2 30
2 31
2 32
2 33
2 34
2 35
2 36
2 37
2 38
2 39
2 40
2 41
2 42
2 43
2 44
2 45
2 46
2 47
2 48
2 49
3 0
3 1
3 2
3 3
3 4
3 5
3 6
3 7
3 8
3 9
3 10
3 11
3 12
3 13
3 14
3 15
3 16
3 17
3 18
3 19
3 20
3 21
3 22
3 23
3 24
3 25
3 26
3 27
3 28
3 29
3 30
3 31
3 32
3 33
3 34
3 35
3 36
3 37
3 38
3 39
3 40
3 41
3 42
3 43
3 44
3 45
3 46
3 47
3 48
3 49
4 0
4 1
4 2
4 3
4 4
4 5
4 6
4 7
4 8
4 9


In [89]:
n_followers

array([3, 5, 1, 4, 3, 1, 4, 3, 6, 3, 2, 1, 2, 1, 1, 7, 3, 2, 5, 2, 7, 5,
       1, 3, 2, 2, 2, 1, 2, 5, 2, 4, 4, 2, 3, 2, 1, 5, 4, 2, 2, 4, 2, 3,
       4, 1, 3, 2, 7, 4, 3, 2, 3, 3, 3, 3, 2, 2, 8, 3, 3, 1, 2, 3, 3, 2,
       2, 1, 8, 2, 2, 3, 3, 2, 5, 4, 1, 4, 1, 2, 1, 3, 3, 3, 3, 5, 5, 1,
       1, 2, 3, 1, 1, 3, 1, 3, 0, 3, 0, 0], dtype=object)

In [70]:
n_followers[7]

4

In [90]:
users[:50]

array([list([8, 1]), list([65, 54, 59, 4]), list([3, 19, 12, 12]),
       list([29, 68, 23]), list([79]),
       list([75, 79, 75, 20, 85, 1, 21, 79, 56, 21]),
       list([84, 32, 59, 8, 49, 86, 74]), list([48, 43]),
       list([24, 93, 23, 66, 66, 30, 44, 49, 39, 54]),
       list([70, 5, 60, 71, 77]), list([65, 0, 14, 39, 42, 19, 50]),
       list([21, 57, 1, 31, 54, 86, 8]), list([49, 37]),
       list([41, 43, 86, 9, 68, 48, 81]),
       list([15, 20, 48, 84, 31, 21, 58]),
       list([85, 48, 10, 94, 58, 82, 82, 58]),
       list([6, 63, 48, 61, 86, 50, 86, 53]), list([20, 40, 68, 1]),
       list([53, 75, 58, 33, 78, 2, 62, 44, 0, 34]),
       list([73, 47, 76, 15, 26]), list([9, 60, 81]),
       list([20, 8, 83, 93, 64, 77, 16, 38, 33]),
       list([1, 68, 49, 85, 40, 37, 29]),
       list([34, 28, 7, 45, 68, 27, 46, 9, 48]),
       list([29, 25, 89, 86, 63]), list([21, 73, 46, 71, 36, 53, 63]),
       list([20, 66, 12, 6, 41, 16, 13, 28, 13, 95]),
       list([43, 51, 4, 71,

In [ ]:
Users().__dict__['read'][4999]
Users().__dict__['read'][5000]

In [ ]:
поменять индексы в матрице связей чтобы начинались с одного

In [ ]:
class Regulators:
    
    def __init__:
        