прописать классы  
прописать элементы игры  
вывести результаты

In [4]:
import numpy as np

In [136]:
class Users(): ## юзеры с подписками на каналы
    
    def __init__(self):
        self.read = [np.random.choice(np.arange(0, 100), np.random.randint(1, 11), replace=False) for i in range(5000)]

In [113]:
users = Users().__dict__['read']
users[:50]

[array([ 7, 51, 63]),
 array([ 8, 30, 49, 56, 67, 40, 97]),
 array([18, 97, 89, 84, 26,  3, 33, 45]),
 array([33, 35, 47, 31, 57, 60, 46, 41, 93]),
 array([68, 20, 79, 22]),
 array([40, 12, 42, 37, 79, 41, 81, 63, 58]),
 array([76]),
 array([46, 43, 58, 17, 63,  7, 37, 74,  0, 77]),
 array([42, 54, 86, 21]),
 array([54, 98]),
 array([79, 22, 12, 53, 29, 74,  6]),
 array([70]),
 array([27, 76,  9]),
 array([20, 39, 96, 74]),
 array([ 8, 53, 98, 75, 17, 56,  2, 88, 73, 55]),
 array([64, 82,  9, 11, 59, 38]),
 array([72, 61, 25, 31,  6, 32]),
 array([28, 14,  2, 41, 82, 52, 22]),
 array([ 7, 88, 75]),
 array([16,  5]),
 array([58, 74, 88, 31, 78]),
 array([86, 21, 92, 84, 89,  0, 54, 68]),
 array([24,  7, 17, 18, 69, 87, 21, 81, 57, 71]),
 array([78, 41, 35, 40, 50]),
 array([51, 58, 89, 54, 97, 61,  8, 86]),
 array([11, 60, 18, 64]),
 array([ 5,  0, 30, 35, 79, 31, 57]),
 array([40, 19, 35, 83, 55]),
 array([13, 49, 17, 56, 68, 32]),
 array([25, 81, 97,  2, 49, 24, 34, 67, 13]),
 array([

In [114]:
for i in users:  #подписки не повторяются
    if len(i) != len(set(i)):
        print(i)

In [357]:
class Publications: ## публикация постов - сенситивные/несенситивные
    
    def __init__(self):
        self.sensitive = np.zeros(100, int)
        for i in range(100):
            self.sensitive[i] = np.random.binomial(n = 1, p = 0.3)

In [372]:
Publications().sensitive

array([0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0])

In [142]:
class Channels(): 
    
    def __init__(self, graph_status):
        
        self.graph_status = graph_status ## матрица связей каналов
        self.graph = np.zeros((100, 100), int)
        
        if self.graph_status:
            for i in range(100):
                for j in range(100):
                    if np.random.binomial(n = 1, p = 0.5) > 0:
                        self.graph[i][j] = np.random.poisson(10, 1)
                        
        self.n_followers = np.zeros(100, list) ## каналы с количеством подписчиков
        for i in range(100): 
            for j in range(5000):
                if i in users[j]: 
                        self.n_followers[i] += 1 

In [144]:
graph = Channels(True).graph
graph

array([[ 0,  9,  9, ...,  0, 13, 10],
       [ 0,  6,  3, ...,  0,  7, 11],
       [ 9, 14,  0, ...,  0,  0,  0],
       ...,
       [10,  0,  0, ...,  9,  0, 14],
       [ 0, 14,  0, ...,  0,  7,  0],
       [18,  0, 16, ..., 10,  0, 13]])

In [173]:
for i in range(100): # вероятность блокировки в первом раунде у всех не более 1%
    if sens_publications[i] == 1:
        print(n_followers[i]/n_followers.sum())

0.01040537611099068
0.009610520991401113
0.009538261435074788
0.010622154779969651
0.009755040104053762
0.009574391213237951
0.009791169882216923
0.010477635667317003
0.009682780547727437
0.009610520991401113
0.011019582339764434
0.010152467663848544
0.00989955921670641
0.009176963653443167
0.010369246332827516
0.008382108533853603
0.0107666738926223
0.009140833875280006
0.011164101452417082
0.009935688994869572
0.009321482766095816
0.009791169882216923
0.010911193005274948
0.009574391213237951
0.01008020810752222
0.009610520991401113
0.01008020810752222
0.010694414336295975
0.010549895223643326
0.009863429438543247
0.010802803670785462
0.009538261435074788
0.010044078329359057
0.009032444540790519
0.009140833875280006
0.010513765445480164
0.01026085699833803
0.009791169882216923
0.010477635667317003
0.009393742322422141
0.01026085699833803
0.010224727220174867


### все здесь

In [8]:
import numpy as np

class Model:
    
    class Users(): ## юзеры с подписками на каналы
    
        def __init__(self):
            self.read = [np.random.choice(np.arange(0, 100), np.random.randint(1, 11), replace=False) for i in range(5000)]
        
        
    class Publications: ## публикация постов - сенситивные/несенситивные - рандомная только для 1 круга?
    
        def __init__(self):
            self.sensitive = np.zeros(100, int)
            for i in range(100):
                self.sensitive[i] = np.random.binomial(n = 1, p = 0.3)
    
    
    class Channels(): 

        def __init__(self, graph_status, users):

            self.graph_status = graph_status ## матрица связей каналов
            self.graph = np.zeros((100, 100), int)

            if self.graph_status:
                for i in range(100):
                    for j in range(100):
                        if np.random.binomial(n = 1, p = 0.5) > 0:
                            self.graph[i][j] = np.random.poisson(10, 1)

            self.n_followers = np.zeros(100, int) ## каналы с количеством подписчиков
            for i in range(100): 
                for j in range(5000):
                    if i in users.read[j]: 
                        self.n_followers[i] += 1 
            
            self.followers = {i: [] for i in range(100)} ## каналы с перечислением подписчиков
            for i in range(100): 
                for j in range(5000):
                    if i in users.read[j]: 
                        self.followers[i].append(j)
    
    
    class Payoff1: ## раздача банов
    
        def __init__(self, n_followers, sens_publications):
            # блокировки
            self.ban = np.zeros(100, int)
            for i in range(100):
                if sens_publications[i] == 1:
                    allus = n_followers.sum()
                    self.ban[i] = np.random.binomial(n = 1, p = n_followers[i]/allus)
    
    
    class Payoff2: ## переход подписчиков
    
        def __init__(self, graph, sens_publications, n_followers, followers, users):
            self.growth = {i: 0 for i in range(100)} 

            for i in range(100):
                for j in range(100):
                    if i != j:
                        if graph[i][j] > 0 and sens_publications[j] != 1:
                            for follower in followers[j]:
                                prob = n_followers[i]/(sum(n_followers[y] for y in list(x for x in users.read[follower]))+n_followers[i])
                                if np.random.binomial(n = 1, p = prob) == 1:
                                    self.growth[i] += 1
    
    class Signal():

        def __init__(self, n_followers, growth):
        # очки за публикацию информативного поста
            self.informative = np.zeros(100, int)
            for i in range(100):
                self.informative[i] = n_followers[i]**2/n_followers.sum()

        # очки за публикацию сенситивного поста
            self.sensitive = np.zeros(100, int)
            for i in range(100):
                self.sensitive[i] = -(n_followers[i]**2)/n_followers.sum() + (1 - n_followers[i]/n_followers.sum())*(n_followers[i] + growth[i])

        # за что больше очков - 1 за сенситивный
            self.post = np.zeros(100, int)
            for i in range(100):
                if self.informative[i] < self.sensitive[i]:
                    self.post[i] = 1
    
    
    def __init__(self):
        
        self.users = self.Users()
        self.sens_publications = self.Publications().sensitive
        self.n_followers = self.Channels(False, self.users).n_followers
        self.followers = self.Channels(False, self.users).followers
        self.graph = self.Channels(True, self.users).graph
        self.ban = self.Payoff1(self.n_followers, self.sens_publications).ban
        self.growth = self.Payoff2(self.graph, self.sens_publications, self.n_followers, self.followers, self.users).growth
        self.signal = self.Signal(self.n_followers, self.growth)
        
model = Model()

print(model.ban)
print(model.growth)
print(model.signal.informative)
print(model.signal.sensitive)
print(model.signal.post)
print(model.graph)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
{0: 1676, 1: 1430, 2: 1339, 3: 1359, 4: 1270, 5: 1415, 6: 1544, 7: 1348, 8: 1338, 9: 1141, 10: 1401, 11: 1417, 12: 1288, 13: 1240, 14: 1218, 15: 1744, 16: 1628, 17: 1645, 18: 1297, 19: 1616, 20: 1652, 21: 1249, 22: 1479, 23: 1685, 24: 1213, 25: 1251, 26: 1776, 27: 1751, 28: 1341, 29: 1433, 30: 1302, 31: 1620, 32: 1271, 33: 1489, 34: 1451, 35: 1276, 36: 1322, 37: 1646, 38: 1439, 39: 1498, 40: 1288, 41: 1225, 42: 1373, 43: 1172, 44: 1264, 45: 1547, 46: 1434, 47: 1467, 48: 1529, 49: 1464, 50: 1126, 51: 1205, 52: 1586, 53: 1688, 54: 1362, 55: 954, 56: 1601, 57: 1689, 58: 1400, 59: 1305, 60: 1264, 61: 1358, 62: 1306, 63: 1363, 64: 1404, 65: 1332, 66: 1328, 67: 1214, 68: 1330, 69: 1703, 70: 1379, 71: 1573, 72: 1392, 73: 1334, 74: 1656, 75: 1222, 76: 1546, 77: 1456, 78: 1249, 79: 1453, 80: 17