прописать классы  
прописать элементы игры  
вывести результаты

In [4]:
import numpy as np

In [136]:
class Users(): ## юзеры с подписками на каналы
    
    def __init__(self):
        self.read = [np.random.choice(np.arange(0, 100), np.random.randint(1, 11), replace=False) for i in range(5000)]

In [113]:
users = Users().__dict__['read']
users[:50]

[array([ 7, 51, 63]),
 array([ 8, 30, 49, 56, 67, 40, 97]),
 array([18, 97, 89, 84, 26,  3, 33, 45]),
 array([33, 35, 47, 31, 57, 60, 46, 41, 93]),
 array([68, 20, 79, 22]),
 array([40, 12, 42, 37, 79, 41, 81, 63, 58]),
 array([76]),
 array([46, 43, 58, 17, 63,  7, 37, 74,  0, 77]),
 array([42, 54, 86, 21]),
 array([54, 98]),
 array([79, 22, 12, 53, 29, 74,  6]),
 array([70]),
 array([27, 76,  9]),
 array([20, 39, 96, 74]),
 array([ 8, 53, 98, 75, 17, 56,  2, 88, 73, 55]),
 array([64, 82,  9, 11, 59, 38]),
 array([72, 61, 25, 31,  6, 32]),
 array([28, 14,  2, 41, 82, 52, 22]),
 array([ 7, 88, 75]),
 array([16,  5]),
 array([58, 74, 88, 31, 78]),
 array([86, 21, 92, 84, 89,  0, 54, 68]),
 array([24,  7, 17, 18, 69, 87, 21, 81, 57, 71]),
 array([78, 41, 35, 40, 50]),
 array([51, 58, 89, 54, 97, 61,  8, 86]),
 array([11, 60, 18, 64]),
 array([ 5,  0, 30, 35, 79, 31, 57]),
 array([40, 19, 35, 83, 55]),
 array([13, 49, 17, 56, 68, 32]),
 array([25, 81, 97,  2, 49, 24, 34, 67, 13]),
 array([

In [114]:
for i in users:  #подписки не повторяются
    if len(i) != len(set(i)):
        print(i)

In [357]:
class Publications: ## публикация постов - сенситивные/несенситивные
    
    def __init__(self):
        self.sensitive = np.zeros(100, int)
        for i in range(100):
            self.sensitive[i] = np.random.binomial(n = 1, p = 0.3)

In [372]:
Publications().sensitive

array([0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0])

In [142]:
class Channels(): 
    
    def __init__(self, graph_status):
        
        self.graph_status = graph_status ## матрица связей каналов
        self.graph = np.zeros((100, 100), int)
        
        if self.graph_status:
            for i in range(100):
                for j in range(100):
                    if np.random.binomial(n = 1, p = 0.5) > 0:
                        self.graph[i][j] = np.random.poisson(10, 1)
                        
        self.n_followers = np.zeros(100, list) ## каналы с количеством подписчиков
        for i in range(100): 
            for j in range(5000):
                if i in users[j]: 
                        self.n_followers[i] += 1 

In [47]:
model.users.read[:50]

[array([46, 40, 44, 18, 39, 21]),
 array([72, 46, 19, 56, 94, 67, 35]),
 array([82, 29,  9, 27, 60, 91]),
 array([61, 58, 65]),
 array([38, 47,  1, 29, 43, 52, 89, 64, 58]),
 array([ 8, 36, 11, 43, 70, 22]),
 array([17, 26, 49, 86, 31, 15]),
 array([63, 42, 91, 43]),
 array([49, 75]),
 array([27, 65, 54, 17, 45,  3, 99]),
 array([67]),
 array([43, 30, 75, 69, 17, 72]),
 array([16, 29]),
 array([ 2,  5, 92, 53, 81, 97, 59, 90, 69]),
 array([96, 28, 87, 51]),
 array([ 6, 33, 37, 79, 30]),
 array([96, 61, 46, 72, 90, 78,  3, 63]),
 array([16, 31, 30, 40, 24,  6, 74, 65]),
 array([96, 23, 65, 39, 13, 41, 94, 46, 93, 97]),
 array([63, 92]),
 array([77, 18, 60, 64, 33, 68,  8, 79]),
 array([85, 27]),
 array([13]),
 array([80, 98, 60, 49, 90]),
 array([75, 72, 83, 20]),
 array([72, 16]),
 array([62, 21, 55, 66]),
 array([21, 98, 24, 52, 97, 91, 47,  2]),
 array([60, 42, 51, 26, 20, 64, 44, 74, 57, 75]),
 array([14,  0, 12]),
 array([36, 41, 42, 57, 32, 96, 93, 62, 82]),
 array([15, 33, 36, 87

In [46]:
n_followers = {i: [] for i in range(10)} 

for i in range(10): 
    for j in range(50):
        if i in model.users.read[j]: 
            n_followers[i].append(j)

print(n_followers)

{0: [29, 45], 1: [4, 39, 43], 2: [13, 27], 3: [9, 16, 45], 4: [42, 47], 5: [13, 36], 6: [15, 17, 33], 7: [40], 8: [5, 20], 9: [2, 31]}


In [145]:
n_followers = Channels(False).n_followers
n_followers

array([306, 277, 288, 266, 283, 272, 290, 264, 255, 288, 294, 275, 254,
       278, 270, 265, 271, 251, 290, 268, 266, 271, 305, 281, 274, 254,
       268, 288, 287, 288, 232, 298, 286, 253, 289, 309, 251, 275, 275,
       295, 258, 271, 261, 279, 302, 265, 272, 291, 310, 285, 279, 266,
       275, 278, 242, 263, 279, 270, 308, 281, 296, 289, 271, 268, 292,
       273, 299, 258, 279, 275, 264, 274, 243, 278, 282, 250, 259, 307,
       295, 276, 303, 253, 291, 252, 295, 284, 271, 277, 267, 290, 278,
       256, 292, 291, 260, 306, 284, 280, 283, 252], dtype=object)

In [144]:
graph = Channels(True).graph
graph

array([[ 0,  9,  9, ...,  0, 13, 10],
       [ 0,  6,  3, ...,  0,  7, 11],
       [ 9, 14,  0, ...,  0,  0,  0],
       ...,
       [10,  0,  0, ...,  9,  0, 14],
       [ 0, 14,  0, ...,  0,  7,  0],
       [18,  0, 16, ..., 10,  0, 13]])

Вероятность детекции регулятором оценивается как количество подписчиков в канале/сумма подписчиков по всем каналам. Обратите внимание, что знаменатель будет больше 5000. С другой стороны, сенситивный пост даёт каналу возможность набора подписчиков. 

In [173]:
for i in range(100): # вероятность блокировки в первом раунде у всех не более 1%
    if sens_publications[i] == 1:
        print(n_followers[i]/n_followers.sum())

0.01040537611099068
0.009610520991401113
0.009538261435074788
0.010622154779969651
0.009755040104053762
0.009574391213237951
0.009791169882216923
0.010477635667317003
0.009682780547727437
0.009610520991401113
0.011019582339764434
0.010152467663848544
0.00989955921670641
0.009176963653443167
0.010369246332827516
0.008382108533853603
0.0107666738926223
0.009140833875280006
0.011164101452417082
0.009935688994869572
0.009321482766095816
0.009791169882216923
0.010911193005274948
0.009574391213237951
0.01008020810752222
0.009610520991401113
0.01008020810752222
0.010694414336295975
0.010549895223643326
0.009863429438543247
0.010802803670785462
0.009538261435074788
0.010044078329359057
0.009032444540790519
0.009140833875280006
0.010513765445480164
0.01026085699833803
0.009791169882216923
0.010477635667317003
0.009393742322422141
0.01026085699833803
0.010224727220174867


In [117]:
import numpy as np

class Model:
    
    class Users(): ## юзеры с подписками на каналы
    
        def __init__(self):
            self.read = [np.random.choice(np.arange(0, 100), np.random.randint(1, 11), replace=False) for i in range(5000)]
        
        
    class Publications: ## публикация постов - сенситивные/несенситивные
    
        def __init__(self):
            self.sensitive = np.zeros(100, int)
            for i in range(100):
                self.sensitive[i] = np.random.binomial(n = 1, p = 0.3)
    
    
    class Channels(): 

        def __init__(self, graph_status, users):

            self.graph_status = graph_status ## матрица связей каналов
            self.graph = np.zeros((100, 100), int)

            if self.graph_status:
                for i in range(100):
                    for j in range(100):
                        if np.random.binomial(n = 1, p = 0.5) > 0:
                            self.graph[i][j] = np.random.poisson(10, 1)

            self.n_followers = np.zeros(100, int) ## каналы с количеством подписчиков
            for i in range(100): 
                for j in range(5000):
                    if i in users.read[j]: 
                        self.n_followers[i] += 1 
            
            self.followers = {i: [] for i in range(100)} ## каналы с перечислением подписчиков
            for i in range(100): 
                for j in range(5000):
                    if i in users.read[j]: 
                        self.followers[i].append(j)
    
    
    class Payoff1: ## раздача банов
    
        def __init__(self, n_followers, sens_publications):
            # блокировки
            self.ban = np.zeros(100, int)
            for i in range(100):
                if sens_publications[i] == 1:
                    allus = n_followers.sum()
                    self.ban[i] = np.random.binomial(n = 1, p = n_followers[i]/allus)
    
    
    class Payoff2: ## переход подписчиков
    
        def __init__(self, graph, sens_publications, n_followers, followers, users):
            self.moving = {i: 0 for i in range(100)} 

            for i in range(100):
                for j in range(100):
                    if i != j:
                        if graph[i][j] > 0 and sens_publications[j] != 1:
                            for follower in followers[j]:
                                prob = n_followers[i]/(sum(n_followers[y] for y in list(x for x in users.read[follower]))+n_followers[i])
                                if np.random.binomial(n = 1, p = prob) == 1:
                                    self.moving[i] += 1

    
    def __init__(self):
        
        self.users = self.Users()
        self.sens_publications = self.Publications().sensitive
        self.n_followers = self.Channels(False, self.users).n_followers
        self.followers = self.Channels(False, self.users).followers
        self.graph = self.Channels(True, self.users).graph
        self.ban = self.Payoff1(model.n_followers, model.sens_publications).ban
        self.moving = Payoff2(model.graph, model.sens_publications, model.n_followers, model.followers, model.users).moving

model = Model()

print(model.ban)
print(model.moving)
print(model.n_followers)
print(model.graph)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
{0: 1076, 1: 1224, 2: 1482, 3: 1214, 4: 1325, 5: 1405, 6: 1636, 7: 1288, 8: 1252, 9: 937, 10: 1187, 11: 1154, 12: 1262, 13: 922, 14: 1206, 15: 1295, 16: 954, 17: 1127, 18: 1221, 19: 1212, 20: 1480, 21: 1443, 22: 1099, 23: 1454, 24: 1628, 25: 1348, 26: 1111, 27: 1251, 28: 1278, 29: 1011, 30: 1244, 31: 1267, 32: 1303, 33: 1162, 34: 942, 35: 1479, 36: 1331, 37: 1372, 38: 1595, 39: 1130, 40: 1014, 41: 1241, 42: 1470, 43: 930, 44: 1036, 45: 1343, 46: 1147, 47: 1249, 48: 1390, 49: 980, 50: 1083, 51: 978, 52: 1440, 53: 1196, 54: 909, 55: 1098, 56: 918, 57: 1283, 58: 1132, 59: 1032, 60: 1202, 61: 1502, 62: 1208, 63: 1096, 64: 1072, 65: 992, 66: 1282, 67: 963, 68: 1290, 69: 1130, 70: 1148, 71: 1282, 72: 1262, 73: 1301, 74: 1259, 75: 1207, 76: 1456, 77: 1272, 78: 1267, 79: 1534, 80: 1286, 81: 13

In [114]:
class Payoff2:
    
    def __init__(self, graph, sens_publications, n_followers, followers, users):
        self.moving = {i: 0 for i in range(100)} 
        
        for i in range(100):
            for j in range(100):
                if i != j:
                    if graph[i][j] > 0 and sens_publications[j] != 1:
                        for follower in followers[j]:
                            prob = n_followers[i]/(sum(n_followers[y] for y in list(x for x in users.read[follower]))+n_followers[i])
                            if np.random.binomial(n = 1, p = prob) == 1:
                                self.moving[i] += 1
            

In [115]:
Payoff2(model.graph, model.sens_publications, model.n_followers, model.followers, model.users).moving

{0: 1033,
 1: 1253,
 2: 1445,
 3: 1267,
 4: 1296,
 5: 1368,
 6: 1657,
 7: 1355,
 8: 1164,
 9: 931,
 10: 1185,
 11: 1109,
 12: 1249,
 13: 926,
 14: 1129,
 15: 1384,
 16: 953,
 17: 1164,
 18: 1178,
 19: 1130,
 20: 1513,
 21: 1429,
 22: 1021,
 23: 1496,
 24: 1576,
 25: 1360,
 26: 1123,
 27: 1279,
 28: 1253,
 29: 1053,
 30: 1239,
 31: 1246,
 32: 1322,
 33: 1228,
 34: 915,
 35: 1439,
 36: 1332,
 37: 1333,
 38: 1531,
 39: 1120,
 40: 997,
 41: 1290,
 42: 1441,
 43: 965,
 44: 955,
 45: 1272,
 46: 1153,
 47: 1175,
 48: 1379,
 49: 977,
 50: 1120,
 51: 993,
 52: 1426,
 53: 1218,
 54: 886,
 55: 1126,
 56: 984,
 57: 1258,
 58: 1165,
 59: 1043,
 60: 1180,
 61: 1484,
 62: 1325,
 63: 1110,
 64: 1130,
 65: 1053,
 66: 1268,
 67: 950,
 68: 1301,
 69: 1129,
 70: 1240,
 71: 1222,
 72: 1234,
 73: 1297,
 74: 1260,
 75: 1234,
 76: 1478,
 77: 1300,
 78: 1275,
 79: 1586,
 80: 1299,
 81: 1243,
 82: 1094,
 83: 1494,
 84: 1053,
 85: 1176,
 86: 1142,
 87: 818,
 88: 1386,
 89: 1253,
 90: 1459,
 91: 1244,
 92: 1405,
