прописать классы  
прописать элементы игры  
вывести результаты

In [3]:
import numpy as np

In [179]:
class Channels(): ## матрица связей каналов
    
    def __init__(self, graph_status):
        
        self.graph_status = graph_status
        self.graph = np.zeros((100, 100), int)
        
        if self.graph_status:
            for i in range(100):
                for j in range(100):
                    if np.random.binomial(n = 1, p = 0.5) > 0:
                        self.graph[i][j] = np.random.poisson(10, 1)

In [341]:
a = Channels(True).graph
a

array([[11,  0,  9, ...,  7, 18,  0],
       [ 0,  0,  0, ...,  0, 10,  0],
       [ 0,  0,  0, ..., 11, 11,  9],
       ...,
       [ 0,  7,  0, ...,  7,  0, 13],
       [ 6, 10,  8, ...,  2,  7, 13],
       [ 0,  0,  0, ...,  0,  0,  8]])

In [136]:
class Users(): ## юзеры с подписками на каналы
    
    def __init__(self):
        self.read = [np.random.choice(np.arange(0, 100), np.random.randint(1, 11), replace=False) for i in range(5000)]

In [113]:
users = Users().__dict__['read']
users[:50]

[array([ 7, 51, 63]),
 array([ 8, 30, 49, 56, 67, 40, 97]),
 array([18, 97, 89, 84, 26,  3, 33, 45]),
 array([33, 35, 47, 31, 57, 60, 46, 41, 93]),
 array([68, 20, 79, 22]),
 array([40, 12, 42, 37, 79, 41, 81, 63, 58]),
 array([76]),
 array([46, 43, 58, 17, 63,  7, 37, 74,  0, 77]),
 array([42, 54, 86, 21]),
 array([54, 98]),
 array([79, 22, 12, 53, 29, 74,  6]),
 array([70]),
 array([27, 76,  9]),
 array([20, 39, 96, 74]),
 array([ 8, 53, 98, 75, 17, 56,  2, 88, 73, 55]),
 array([64, 82,  9, 11, 59, 38]),
 array([72, 61, 25, 31,  6, 32]),
 array([28, 14,  2, 41, 82, 52, 22]),
 array([ 7, 88, 75]),
 array([16,  5]),
 array([58, 74, 88, 31, 78]),
 array([86, 21, 92, 84, 89,  0, 54, 68]),
 array([24,  7, 17, 18, 69, 87, 21, 81, 57, 71]),
 array([78, 41, 35, 40, 50]),
 array([51, 58, 89, 54, 97, 61,  8, 86]),
 array([11, 60, 18, 64]),
 array([ 5,  0, 30, 35, 79, 31, 57]),
 array([40, 19, 35, 83, 55]),
 array([13, 49, 17, 56, 68, 32]),
 array([25, 81, 97,  2, 49, 24, 34, 67, 13]),
 array([

In [114]:
for i in users:  #подписки не повторяются
    if len(i) != len(set(i)):
        print(i)

In [357]:
class Publications: ## публикация постов - сенситивные/несенситивные
    
    def __init__(self):
        self.sensitive = np.zeros(100, int)
        for i in range(100):
            self.sensitive[i] = np.random.binomial(n = 1, p = 0.3)

In [372]:
Publications().sensitive

array([0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0])

In [139]:
users = Users().__dict__['read']
users

[array([68, 22]),
 array([71]),
 array([37, 49, 30, 51, 43, 74, 35]),
 array([90]),
 array([54, 48, 53,  8, 46, 39, 79, 28]),
 array([28,  4, 45]),
 array([ 2,  9, 84, 16, 35, 41, 27]),
 array([53, 72, 96]),
 array([80, 82]),
 array([24, 70,  0, 65, 92, 90, 85, 99, 86, 48]),
 array([64, 58, 27, 74,  6, 50]),
 array([67, 86, 56, 38, 80,  6, 23, 59, 64, 37]),
 array([38, 90, 27, 96]),
 array([37]),
 array([ 2, 59, 60, 75, 37, 21,  0]),
 array([82, 48]),
 array([78, 23, 20]),
 array([ 8, 72]),
 array([73, 38, 17, 48, 10, 18, 63, 89, 83]),
 array([ 0, 93, 41]),
 array([ 2,  4, 33, 78, 51]),
 array([20, 56, 17, 16]),
 array([16,  0, 34, 41, 78,  5, 18]),
 array([97, 55,  4, 99, 84, 23, 59, 31, 96, 76]),
 array([97, 34, 44, 64, 91, 93]),
 array([55, 37, 21, 45, 16]),
 array([55, 77, 18, 46, 58, 64]),
 array([16, 53, 24, 43, 79, 84, 15, 96]),
 array([13, 92, 54, 95, 47, 55, 25]),
 array([20, 40, 74, 61,  7, 89, 32]),
 array([ 9, 64, 76, 52, 20,  7]),
 array([18, 39, 22,  9, 31, 41, 19, 33, 71

In [142]:
class Channels(): 
    
    def __init__(self, graph_status):
        
        self.graph_status = graph_status ## матрица связей каналов
        self.graph = np.zeros((100, 100), int)
        
        if self.graph_status:
            for i in range(100):
                for j in range(100):
                    if np.random.binomial(n = 1, p = 0.5) > 0:
                        self.graph[i][j] = np.random.poisson(10, 1)
                        
        self.n_followers = np.zeros(100, list) ## каналы с количеством подписчиков
        for i in range(100): 
            for j in range(5000):
                if i in users[j]: 
                        self.n_followers[i] += 1 

In [143]:
Channels(False).n_followers

array([306, 277, 288, 266, 283, 272, 290, 264, 255, 288, 294, 275, 254,
       278, 270, 265, 271, 251, 290, 268, 266, 271, 305, 281, 274, 254,
       268, 288, 287, 288, 232, 298, 286, 253, 289, 309, 251, 275, 275,
       295, 258, 271, 261, 279, 302, 265, 272, 291, 310, 285, 279, 266,
       275, 278, 242, 263, 279, 270, 308, 281, 296, 289, 271, 268, 292,
       273, 299, 258, 279, 275, 264, 274, 243, 278, 282, 250, 259, 307,
       295, 276, 303, 253, 291, 252, 295, 284, 271, 277, 267, 290, 278,
       256, 292, 291, 260, 306, 284, 280, 283, 252], dtype=object)

In [ ]:
class Regulators:
    
    def __init__:
        